/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Jf_MenuDev extends javax.swing.JFrame {

    /**
     * Creates new form jframeFacturaIvaAcred
     */
    public Jf_MenuDev() {
        initComponents();
        preConfiguracion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jm_Inicio = new javax.swing.JMenu();
        jmItemDeterIvaFavor = new javax.swing.JMenuItem();
        jmItemFactIvaAcred = new javax.swing.JMenuItem();
        jmItemAuxIvaAcred = new javax.swing.JMenuItem();
        jmItemRetenIvaMes = new javax.swing.JMenuItem();
        jmItemRetenIvaPagMes = new javax.swing.JMenuItem();
        jmItemActosTasa16 = new javax.swing.JMenuItem();
        jmItemActosTasaCero = new javax.swing.JMenuItem();
        jmItemRelacDepos = new javax.swing.JMenuItem();
        jmItemAuxDepos = new javax.swing.JMenuItem();
        Jm_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integracion Iva");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo_circulo2.png"))); // NOI18N
        jpanelInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        getContentPane().add(jpanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        Jm_Inicio.setBorder(null);
        Jm_Inicio.setText("INICIO");

        jmItemDeterIvaFavor.setText("DETERMINACION DE IVA A FAVOR");
        Jm_Inicio.add(jmItemDeterIvaFavor);

        jmItemFactIvaAcred.setBackground(new java.awt.Color(153, 204, 255));
        jmItemFactIvaAcred.setText("FACTURAS IVA ACRED\n");
        jmItemFactIvaAcred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemFactIvaAcredActionPerformed(evt);
            }
        });
        Jm_Inicio.add(jmItemFactIvaAcred);

        jmItemAuxIvaAcred.setText("AUXILIAR IVA ACREDITABLE");
        Jm_Inicio.add(jmItemAuxIvaAcred);

        jmItemRetenIvaMes.setText("RETENCIONES DE IVA DEL MES");
        Jm_Inicio.add(jmItemRetenIvaMes);

        jmItemRetenIvaPagMes.setText("RETENCIONES DE IVA PAGADAS DEL MES");
        Jm_Inicio.add(jmItemRetenIvaPagMes);

        jmItemActosTasa16.setText("ACTOS TASA 16%");
        Jm_Inicio.add(jmItemActosTasa16);

        jmItemActosTasaCero.setText("ACTOS TASA 0%");
        Jm_Inicio.add(jmItemActosTasaCero);

        jmItemRelacDepos.setText("RELACION DEPOSITOS");
        Jm_Inicio.add(jmItemRelacDepos);

        jmItemAuxDepos.setText("AUXILIAR DE DEPOSITOS");
        Jm_Inicio.add(jmItemAuxDepos);

        jMenuBar1.add(Jm_Inicio);

        Jm_Salir.setText("SALIR");
        jMenuBar1.add(Jm_Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemFactIvaAcredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemFactIvaAcredActionPerformed
        Jf_FacturasIvaAcred facturasIvaAcred = new Jf_FacturasIvaAcred();
        facturasIvaAcred.setVisible(true);
        //extra: codigo para evitar que se abran dos

    }//GEN-LAST:event_jmItemFactIvaAcredActionPerformed

    /*
    METODOS DEL FRAME
     */
    /**
     * Metodo que preconfigura el diseño del jframe
     */
    private void preConfiguracion() {
        //Posicion del jframe

        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //Elementos adicionales
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jm_Inicio;
    private javax.swing.JMenu Jm_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmItemActosTasa16;
    private javax.swing.JMenuItem jmItemActosTasaCero;
    private javax.swing.JMenuItem jmItemAuxDepos;
    private javax.swing.JMenuItem jmItemAuxIvaAcred;
    private javax.swing.JMenuItem jmItemDeterIvaFavor;
    private javax.swing.JMenuItem jmItemFactIvaAcred;
    private javax.swing.JMenuItem jmItemRelacDepos;
    private javax.swing.JMenuItem jmItemRetenIvaMes;
    private javax.swing.JMenuItem jmItemRetenIvaPagMes;
    private javax.swing.JPanel jpanelInicio;
    // End of variables declaration//GEN-END:variables
}
