/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.IvaAcredController;
import Controllers.XmlDatos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Macktronica
 */
public class jf_Principal extends javax.swing.JFrame {

    /**
     * Creates new form jf_Principal
     */
    public jf_Principal() {

        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        this.setSize(width / 2, height / 2);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIvaAcred = new javax.swing.JTable();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jm_GlobalBancos = new javax.swing.JMenu();
        jm_Banorte = new javax.swing.JMenu();
        jm_ValorActosIngr = new javax.swing.JMenu();
        jm_IvaAcred = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgroEcologia Devoluciones");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        tablaIvaAcred.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaIvaAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaIvaAcred.setEnabled(false);
        jScrollPane1.setViewportView(tablaIvaAcred);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 458));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 155));

        jMenuPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuPrincipal.setEnabled(false);

        jm_GlobalBancos.setText("Global Bancos");
        jMenuPrincipal.add(jm_GlobalBancos);

        jm_Banorte.setText("Banorte");
        jm_Banorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_BanorteMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jm_Banorte);

        jm_ValorActosIngr.setText("Valor de Actos Ingresos");
        jMenuPrincipal.add(jm_ValorActosIngr);

        jm_IvaAcred.setText("Iva ACRED");
        jm_IvaAcred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_IvaAcredMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jm_IvaAcred);

        setJMenuBar(jMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_BanorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_BanorteMouseClicked


    }//GEN-LAST:event_jm_BanorteMouseClicked

    private void jm_IvaAcredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_IvaAcredMouseClicked
        tablaIvaAcred.removeAll();
        if (tablaIvaAcred.getRowCount() == 0) {
            inicializarTablaIva();
        }


    }//GEN-LAST:event_jm_IvaAcredMouseClicked

    private void inicializarTablaIva() {
        DefaultTableModel tablaIva = new DefaultTableModel();
        String[] titulos = {"#Factura", "Fecha Factura", "#Poliza", "Fecha Poliza", "Folio Fiscal", "Conceptos XML", "Sub-Total", "IVA", "IVA Retenido", "ISR Retenido",
            "Total", "Cruce: Estado de cuenta", "Pago: Fecha", "Pago: Concepto S.E.C", "Pago: Forma Pago", "RFC Proveedor", "Nombre Proveedor", "Concepto", "Relación con Activ.",
            "Cta. de la que se realiza el pago", "Observaciones"};
        System.out.println("tamaño: " + titulos.length);
        tablaIva.setColumnIdentifiers(titulos);
        IvaAcredController ivaAcred = new IvaAcredController();

        String URL = "I:\\Dac\\Enero 01";
        List<XmlDatos> llenarDatosTabla = ivaAcred.datosDevolucionIva(URL);
        for (int i = 0; i < llenarDatosTabla.size(); i++) {
            tablaIva.addRow(new Object[]{"N/D", llenarDatosTabla.get(i).getFechaFactura(), "N/D", "N/D", llenarDatosTabla.get(i).getFolioFiscal(),
                llenarDatosTabla.get(i).getConceptoXml(), llenarDatosTabla.get(i).getSubTotal(), "N/D", "N/D", "N/D", llenarDatosTabla.get(i).getTotal(),
                "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D",});
        }
        tablaIvaAcred.setModel(tablaIva);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jm_Banorte;
    private javax.swing.JMenu jm_GlobalBancos;
    private javax.swing.JMenu jm_IvaAcred;
    private javax.swing.JMenu jm_ValorActosIngr;
    private javax.swing.JTable tablaIvaAcred;
    // End of variables declaration//GEN-END:variables
}
