/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.IvaAcredController;
import Controllers.XmlDatos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Macktronica
 */
public class jf_Principal extends javax.swing.JFrame {

    /**
     * Creates new form jf_Principal
     */
    public jf_Principal() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        this.setSize(width / 2, height / 2);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DevIva = new javax.swing.JTable();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jm_GlobalBancos = new javax.swing.JMenu();
        jm_Banorte = new javax.swing.JMenu();
        jm_ValorActosIngr = new javax.swing.JMenu();
        jm_IvaAcred = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgroEcologia Devoluciones");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        tb_DevIva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_DevIva);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jm_GlobalBancos.setText("Global Bancos");
        jMenuPrincipal.add(jm_GlobalBancos);

        jm_Banorte.setText("Banorte");
        jm_Banorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_BanorteMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jm_Banorte);

        jm_ValorActosIngr.setText("Valor de Actos Ingresos");
        jMenuPrincipal.add(jm_ValorActosIngr);

        jm_IvaAcred.setText("Iva ACRED");
        jm_IvaAcred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_IvaAcredMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jm_IvaAcred);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_BanorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_BanorteMouseClicked


    }//GEN-LAST:event_jm_BanorteMouseClicked

    private void jm_IvaAcredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_IvaAcredMouseClicked
        DefaultTableModel tablaDevIva = new DefaultTableModel();
        IvaAcredController ivaAcred = new IvaAcredController();
        String URL = "I:\\Dac\\Enero 01";
        List<XmlDatos> llenarDatosTabla = ivaAcred.datosDevolucionIva(URL);
        for (int i = 0; i < llenarDatosTabla.size(); i++) {
            System.out.println("datos tabla: " + llenarDatosTabla.get(i).getTotal());
        }

    }//GEN-LAST:event_jm_IvaAcredMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jm_Banorte;
    private javax.swing.JMenu jm_GlobalBancos;
    private javax.swing.JMenu jm_IvaAcred;
    private javax.swing.JMenu jm_ValorActosIngr;
    private javax.swing.JTable tb_DevIva;
    // End of variables declaration//GEN-END:variables
}
