/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.IvaAcredController;
import Models.PolizaDatos;
import Models.AuxIvaAcred;
import Controllers.AuxIvaAcredController;
import Controllers.ControllerAction;
import Controllers.GeneradorExcel;
import Models.RetencionIvaMes;
import Models.XmlDatos;
import Models.RetencionIvaPagadaMes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.text.DecimalFormat;

/**
 *
 * @author horusblack
 */
public class jfGlobal extends javax.swing.JFrame {

    private DefaultTableModel tablaIva;
    private DefaultTableModel defaultTableIva;
    private String periodo, asunto, empresa;
    private int numRegistros, numAnio;
    private double totalAuxCred;
    private ControllerAction controllerAction;
    private IvaAcredController ivaAcred;
    private List<PolizaDatos> listPolizaDatos;
    private AuxIvaAcred auxIvaAcred;
    private List<AuxIvaAcred> listAuxIvaAcreds;
    private List<RetencionIvaMes> listRetencionIvaMeses;
    private List<RetencionIvaPagadaMes> listRetencionIvaPagadaMes;
    private GeneradorExcel generadorExcel;

    /**
     * Creates new form jfGlobal
     */
    public jfGlobal() {
        initComponents();
        preConfiguracion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Filtro = new javax.swing.JPanel();
        calendarMes = new com.toedter.calendar.JMonthChooser();
        calendarAnio = new com.toedter.calendar.JYearChooser();
        btnProcesarIva = new javax.swing.JButton();
        btnXmlCargar = new javax.swing.JButton();
        panel_contenidoGlobal = new javax.swing.JPanel();
        tp_Secciones = new javax.swing.JTabbedPane();
        panel_Det_Iva_Favor = new javax.swing.JPanel();
        panel_Cien_FIA = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        SpIva = new javax.swing.JScrollPane();
        tablaIvaAcred = new javax.swing.JTable();
        ScrollTotalIva = new javax.swing.JScrollPane();
        tablaTotalIva = new javax.swing.JTable();
        btnGuardarIva = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        panelConcepto = new javax.swing.JPanel();
        scrollPaneConcepto = new javax.swing.JScrollPane();
        txta_Concepto = new javax.swing.JTextArea();
        lb_100 = new javax.swing.JLabel();
        panel_Aux_IA = new javax.swing.JPanel();
        panel_CabecerAuxIva = new javax.swing.JPanel();
        lbT1 = new javax.swing.JLabel();
        lbT_mesAuxIvaAcred = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_dataIvaAcred = new javax.swing.JPanel();
        panel_TablaIvaAcred = new javax.swing.JPanel();
        SpIva1 = new javax.swing.JScrollPane();
        tabla_ivaAuxAcred = new javax.swing.JTable();
        panel_resultIvaAcred = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_totalAuxIvaAcred = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_ExportExcel_AuxIvaAcred = new javax.swing.JButton();
        panel_RIM = new javax.swing.JPanel();
        panel_detRIM = new javax.swing.JPanel();
        SpIva4 = new javax.swing.JScrollPane();
        tabla_RIM = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_ExportExcel_RIM = new javax.swing.JButton();
        lb_RIM = new javax.swing.JLabel();
        panel_RIPM = new javax.swing.JPanel();
        panel_RetIvaMes1 = new javax.swing.JPanel();
        SpIva3 = new javax.swing.JScrollPane();
        tabla_RetIvaMesPagada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_ExportExcel_RIMP = new javax.swing.JButton();
        lb_RIPM = new javax.swing.JLabel();
        panel_AT_16 = new javax.swing.JPanel();
        panel_AT_Cero = new javax.swing.JPanel();
        panel_RelacionDep = new javax.swing.JPanel();
        panel_AuxDep = new javax.swing.JPanel();
        panel_AuxDepositos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_AuxDepositos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Filtro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        calendarMes.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Mes"));

        calendarAnio.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Año"));

        btnProcesarIva.setBackground(new java.awt.Color(153, 204, 255));
        btnProcesarIva.setText("Procesar");
        btnProcesarIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarIvaActionPerformed(evt);
            }
        });

        btnXmlCargar.setText("Cargar Carpeta XML");
        btnXmlCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXmlCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_FiltroLayout = new javax.swing.GroupLayout(panel_Filtro);
        panel_Filtro.setLayout(panel_FiltroLayout);
        panel_FiltroLayout.setHorizontalGroup(
            panel_FiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calendarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_FiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcesarIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXmlCargar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_FiltroLayout.setVerticalGroup(
            panel_FiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_FiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_FiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(calendarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calendarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_FiltroLayout.createSequentialGroup()
                        .addComponent(btnProcesarIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXmlCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel_contenidoGlobal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_contenidoGlobal.setAutoscrolls(true);

        javax.swing.GroupLayout panel_Det_Iva_FavorLayout = new javax.swing.GroupLayout(panel_Det_Iva_Favor);
        panel_Det_Iva_Favor.setLayout(panel_Det_Iva_FavorLayout);
        panel_Det_Iva_FavorLayout.setHorizontalGroup(
            panel_Det_Iva_FavorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        panel_Det_Iva_FavorLayout.setVerticalGroup(
            panel_Det_Iva_FavorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        tp_Secciones.addTab("DETERMINACION DE  IVA A FAVOR", panel_Det_Iva_Favor);

        panel_Cien_FIA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SpIva.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaIvaAcred.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaIvaAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaIvaAcred.setToolTipText("");
        tablaIvaAcred.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        SpIva.setViewportView(tablaIvaAcred);

        ScrollTotalIva.setBorder(javax.swing.BorderFactory.createTitledBorder("Totales"));

        tablaTotalIva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaTotalIva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollTotalIva.setViewportView(tablaTotalIva);

        btnGuardarIva.setBackground(new java.awt.Color(51, 204, 255));
        btnGuardarIva.setText("Guardar");

        btnPDF.setBackground(new java.awt.Color(204, 0, 51));
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("Generar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        panelConcepto.setBorder(javax.swing.BorderFactory.createTitledBorder("Concepto XML Completo"));

        txta_Concepto.setColumns(30);
        txta_Concepto.setRows(5);
        txta_Concepto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txta_Concepto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txta_Concepto.setEnabled(false);
        scrollPaneConcepto.setViewportView(txta_Concepto);

        javax.swing.GroupLayout panelConceptoLayout = new javax.swing.GroupLayout(panelConcepto);
        panelConcepto.setLayout(panelConceptoLayout);
        panelConceptoLayout.setHorizontalGroup(
            panelConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConceptoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneConcepto)
                .addContainerGap())
        );
        panelConceptoLayout.setVerticalGroup(
            panelConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneConcepto)
        );

        lb_100.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpIva, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(ScrollTotalIva, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(340, 340, 340))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(panelConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lb_100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(591, 591, 591))))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpIva, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addComponent(btnPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarIva)
                        .addGap(10, 10, 10))
                    .addComponent(ScrollTotalIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panel_Cien_FIALayout = new javax.swing.GroupLayout(panel_Cien_FIA);
        panel_Cien_FIA.setLayout(panel_Cien_FIALayout);
        panel_Cien_FIALayout.setHorizontalGroup(
            panel_Cien_FIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Cien_FIALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_Cien_FIALayout.setVerticalGroup(
            panel_Cien_FIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Cien_FIALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp_Secciones.addTab("100% FACTURAS DE IVA ACRED", panel_Cien_FIA);

        panel_CabecerAuxIva.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbT1.setFont(new java.awt.Font("Source Code Pro Medium", 1, 12)); // NOI18N
        lbT1.setText("RELACIÓN DEL 100% DE IVA ACREDITABLE");

        lbT_mesAuxIvaAcred.setFont(new java.awt.Font("Source Code Pro Medium", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Source Code Pro Medium", 1, 12)); // NOI18N
        jLabel1.setText("CUENTA 1151-001-000-000");

        javax.swing.GroupLayout panel_CabecerAuxIvaLayout = new javax.swing.GroupLayout(panel_CabecerAuxIva);
        panel_CabecerAuxIva.setLayout(panel_CabecerAuxIvaLayout);
        panel_CabecerAuxIvaLayout.setHorizontalGroup(
            panel_CabecerAuxIvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CabecerAuxIvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CabecerAuxIvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbT1)
                    .addComponent(lbT_mesAuxIvaAcred)
                    .addComponent(jLabel1))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        panel_CabecerAuxIvaLayout.setVerticalGroup(
            panel_CabecerAuxIvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CabecerAuxIvaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbT_mesAuxIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_dataIvaAcred.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_TablaIvaAcred.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpIva1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla_ivaAuxAcred.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla_ivaAuxAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_ivaAuxAcred.setToolTipText("");
        tabla_ivaAuxAcred.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_ivaAuxAcred.setEnabled(false);
        SpIva1.setViewportView(tabla_ivaAuxAcred);

        javax.swing.GroupLayout panel_TablaIvaAcredLayout = new javax.swing.GroupLayout(panel_TablaIvaAcred);
        panel_TablaIvaAcred.setLayout(panel_TablaIvaAcredLayout);
        panel_TablaIvaAcredLayout.setHorizontalGroup(
            panel_TablaIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel_TablaIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TablaIvaAcredLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SpIva1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_TablaIvaAcredLayout.setVerticalGroup(
            panel_TablaIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
            .addGroup(panel_TablaIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TablaIvaAcredLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SpIva1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panel_resultIvaAcred.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table_totalAuxIvaAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_totalAuxIvaAcred.setEnabled(false);
        jScrollPane1.setViewportView(table_totalAuxIvaAcred);

        jLabel2.setText("Exportar");

        btn_ExportExcel_AuxIvaAcred.setBackground(new java.awt.Color(102, 255, 153));
        btn_ExportExcel_AuxIvaAcred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excel-icon72.png"))); // NOI18N
        btn_ExportExcel_AuxIvaAcred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportExcel_AuxIvaAcredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ExportExcel_AuxIvaAcred, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(btn_ExportExcel_AuxIvaAcred, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_resultIvaAcredLayout = new javax.swing.GroupLayout(panel_resultIvaAcred);
        panel_resultIvaAcred.setLayout(panel_resultIvaAcredLayout);
        panel_resultIvaAcredLayout.setHorizontalGroup(
            panel_resultIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_resultIvaAcredLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel_resultIvaAcredLayout.setVerticalGroup(
            panel_resultIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultIvaAcredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_resultIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_dataIvaAcredLayout = new javax.swing.GroupLayout(panel_dataIvaAcred);
        panel_dataIvaAcred.setLayout(panel_dataIvaAcredLayout);
        panel_dataIvaAcredLayout.setHorizontalGroup(
            panel_dataIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataIvaAcredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dataIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_resultIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_TablaIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_dataIvaAcredLayout.setVerticalGroup(
            panel_dataIvaAcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataIvaAcredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_TablaIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_resultIvaAcred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_Aux_IALayout = new javax.swing.GroupLayout(panel_Aux_IA);
        panel_Aux_IA.setLayout(panel_Aux_IALayout);
        panel_Aux_IALayout.setHorizontalGroup(
            panel_Aux_IALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Aux_IALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Aux_IALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_dataIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_CabecerAuxIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_Aux_IALayout.setVerticalGroup(
            panel_Aux_IALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Aux_IALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_CabecerAuxIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_dataIvaAcred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp_Secciones.addTab("AUXILIAR IVA ACREDITABLE", panel_Aux_IA);

        panel_detRIM.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpIva4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla_RIM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla_RIM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_RIM.setToolTipText("");
        tabla_RIM.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_RIM.setEnabled(false);
        SpIva4.setViewportView(tabla_RIM);

        jLabel4.setText("Exportar");

        btn_ExportExcel_RIM.setBackground(new java.awt.Color(102, 255, 153));
        btn_ExportExcel_RIM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excel-icon72.png"))); // NOI18N
        btn_ExportExcel_RIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportExcel_RIMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ExportExcel_RIM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btn_ExportExcel_RIM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_RIM.setFont(new java.awt.Font("Source Code Pro Medium", 1, 14)); // NOI18N

        javax.swing.GroupLayout panel_detRIMLayout = new javax.swing.GroupLayout(panel_detRIM);
        panel_detRIM.setLayout(panel_detRIMLayout);
        panel_detRIMLayout.setHorizontalGroup(
            panel_detRIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_detRIMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_detRIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpIva4, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(panel_detRIMLayout.createSequentialGroup()
                        .addGroup(panel_detRIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_RIM))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_detRIMLayout.setVerticalGroup(
            panel_detRIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_detRIMLayout.createSequentialGroup()
                .addComponent(lb_RIM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpIva4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_RIMLayout = new javax.swing.GroupLayout(panel_RIM);
        panel_RIM.setLayout(panel_RIMLayout);
        panel_RIMLayout.setHorizontalGroup(
            panel_RIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RIMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_detRIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_RIMLayout.setVerticalGroup(
            panel_RIMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RIMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_detRIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp_Secciones.addTab("RENTENCIONES DE IVA DEL MES", panel_RIM);

        panel_RetIvaMes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpIva3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla_RetIvaMesPagada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla_RetIvaMesPagada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_RetIvaMesPagada.setToolTipText("");
        tabla_RetIvaMesPagada.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_RetIvaMesPagada.setEnabled(false);
        SpIva3.setViewportView(tabla_RetIvaMesPagada);

        jLabel3.setText("Exportar");

        btn_ExportExcel_RIMP.setBackground(new java.awt.Color(102, 255, 153));
        btn_ExportExcel_RIMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excel-icon72.png"))); // NOI18N
        btn_ExportExcel_RIMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportExcel_RIMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ExportExcel_RIMP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btn_ExportExcel_RIMP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_RIPM.setFont(new java.awt.Font("Source Code Pro Medium", 1, 14)); // NOI18N

        javax.swing.GroupLayout panel_RetIvaMes1Layout = new javax.swing.GroupLayout(panel_RetIvaMes1);
        panel_RetIvaMes1.setLayout(panel_RetIvaMes1Layout);
        panel_RetIvaMes1Layout.setHorizontalGroup(
            panel_RetIvaMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RetIvaMes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_RetIvaMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpIva3, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(panel_RetIvaMes1Layout.createSequentialGroup()
                        .addGroup(panel_RetIvaMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_RIPM))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_RetIvaMes1Layout.setVerticalGroup(
            panel_RetIvaMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_RetIvaMes1Layout.createSequentialGroup()
                .addComponent(lb_RIPM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpIva3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_RIPMLayout = new javax.swing.GroupLayout(panel_RIPM);
        panel_RIPM.setLayout(panel_RIPMLayout);
        panel_RIPMLayout.setHorizontalGroup(
            panel_RIPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RIPMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_RetIvaMes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_RIPMLayout.setVerticalGroup(
            panel_RIPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RIPMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_RetIvaMes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp_Secciones.addTab("RET DE IVA PAGADAS EN EL MES", panel_RIPM);

        javax.swing.GroupLayout panel_AT_16Layout = new javax.swing.GroupLayout(panel_AT_16);
        panel_AT_16.setLayout(panel_AT_16Layout);
        panel_AT_16Layout.setHorizontalGroup(
            panel_AT_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        panel_AT_16Layout.setVerticalGroup(
            panel_AT_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        tp_Secciones.addTab("ACTOS TASA 16%", panel_AT_16);

        javax.swing.GroupLayout panel_AT_CeroLayout = new javax.swing.GroupLayout(panel_AT_Cero);
        panel_AT_Cero.setLayout(panel_AT_CeroLayout);
        panel_AT_CeroLayout.setHorizontalGroup(
            panel_AT_CeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        panel_AT_CeroLayout.setVerticalGroup(
            panel_AT_CeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        tp_Secciones.addTab("ACTOS TASA 0%", panel_AT_Cero);

        javax.swing.GroupLayout panel_RelacionDepLayout = new javax.swing.GroupLayout(panel_RelacionDep);
        panel_RelacionDep.setLayout(panel_RelacionDepLayout);
        panel_RelacionDepLayout.setHorizontalGroup(
            panel_RelacionDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        panel_RelacionDepLayout.setVerticalGroup(
            panel_RelacionDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        tp_Secciones.addTab("RELACION DEPOSITOS", panel_RelacionDep);

        panel_AuxDepositos.setBorder(javax.swing.BorderFactory.createTitledBorder("INTEGRACIÓN DE DEPOSITOS BANCARIOS"));

        tabla_AuxDepositos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_AuxDepositos);

        javax.swing.GroupLayout panel_AuxDepositosLayout = new javax.swing.GroupLayout(panel_AuxDepositos);
        panel_AuxDepositos.setLayout(panel_AuxDepositosLayout);
        panel_AuxDepositosLayout.setHorizontalGroup(
            panel_AuxDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AuxDepositosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_AuxDepositosLayout.setVerticalGroup(
            panel_AuxDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AuxDepositosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_AuxDepLayout = new javax.swing.GroupLayout(panel_AuxDep);
        panel_AuxDep.setLayout(panel_AuxDepLayout);
        panel_AuxDepLayout.setHorizontalGroup(
            panel_AuxDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AuxDepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_AuxDepositos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_AuxDepLayout.setVerticalGroup(
            panel_AuxDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AuxDepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_AuxDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        tp_Secciones.addTab("AUXILIAR  DE DEPOSITOS", panel_AuxDep);

        javax.swing.GroupLayout panel_contenidoGlobalLayout = new javax.swing.GroupLayout(panel_contenidoGlobal);
        panel_contenidoGlobal.setLayout(panel_contenidoGlobalLayout);
        panel_contenidoGlobalLayout.setHorizontalGroup(
            panel_contenidoGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenidoGlobalLayout.createSequentialGroup()
                .addComponent(tp_Secciones)
                .addContainerGap())
        );
        panel_contenidoGlobalLayout.setVerticalGroup(
            panel_contenidoGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenidoGlobalLayout.createSequentialGroup()
                .addComponent(tp_Secciones, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_contenidoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Filtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panel_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_contenidoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed

    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnProcesarIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarIvaActionPerformed
        //XML DATOS
        int intNumMes = calendarMes.getMonth();

        int intNumYear = calendarAnio.getYear();
        String[] numeroMes = {"01 Enero", "02 Febrero", "03 Marzo", "04 Abril", "05 Mayo", "06 Junio", "07 Julio", "08 Agosto", "09 Septiembre", "10 Octubre",
            "11 Noviembre", "12 Diciembre"};
        String[] nombreDelMes = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre",
            "Noviembre", "Diciembre"};

        String urlMes = numeroMes[intNumMes];
        periodo = nombreDelMes[intNumMes];
        numAnio = intNumYear;
        tablaIvaAcred.removeAll();
        //Inicializar Tabla 100 Iva Acred
        inicializarTablaIva(urlMes, periodo, intNumMes, intNumYear);
        inicializarTablaTotalIva();
        //Ver si es posible cambiar el nombre de las carpetas para que tenga un mismo formato y sea mas facil acceder        
        //Inicializar Tabla Auxiliar Iva Acred
        inicializarAuxIvaAcred(nombreDelMes[intNumMes], intNumMes, intNumYear);
        inicializarTablaTotalAuxAcred(nombreDelMes[intNumMes], intNumYear, totalAuxCred);
        //Inicializar Tabla RetencionIvaMes
        inicializarTablaRetencionIvaMes(nombreDelMes[intNumMes], intNumMes, intNumYear);
        //Inicializar Tabla RetencionIvaMesPagadas
        inicializarTablaRetencionIvaMesPagadas(nombreDelMes[intNumMes], intNumMes, intNumYear);
    }//GEN-LAST:event_btnProcesarIvaActionPerformed

    private void btnXmlCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXmlCargarActionPerformed
        JFileChooser selectorCarpetaXml = new JFileChooser();
        selectorCarpetaXml.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = selectorCarpetaXml.showOpenDialog(this);
        if (resultado == 0) {
            File carpetaSeleccionada = selectorCarpetaXml.getSelectedFile();
            String rutaCarpeta = carpetaSeleccionada.getAbsolutePath();
            ivaAcred = new IvaAcredController();
            if (ivaAcred.validarArchivosCarpeta(rutaCarpeta)) {
                //Pendiente metodo que empalme xml nuevos con datos de la tabla(Que vienen desde la BD)
                JOptionPane.showMessageDialog(this, "Anexando archivos a tabla");
            } else {
                JOptionPane.showMessageDialog(this, "No existen documentos XML dentro de la carpeta seleccionada");
            }
        }

    }//GEN-LAST:event_btnXmlCargarActionPerformed

    private void btn_ExportExcel_AuxIvaAcredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportExcel_AuxIvaAcredActionPerformed
        generadorExcel = new GeneradorExcel();
        generadorExcel.generarExcelAuxiliarIvaAcred(tabla_ivaAuxAcred, table_totalAuxIvaAcred, "AUXILIAR IVA A CRED", periodo.toUpperCase(), String.valueOf(numAnio));
    }//GEN-LAST:event_btn_ExportExcel_AuxIvaAcredActionPerformed

    private void btn_ExportExcel_RIMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportExcel_RIMPActionPerformed
        generadorExcel = new GeneradorExcel();
        generadorExcel.generarExcelIvaRetenidoMesPagado(tabla_RetIvaMesPagada, "RET DE IVA PAGADAS EN EL MES", periodo.toUpperCase(), String.valueOf(numAnio));
    }//GEN-LAST:event_btn_ExportExcel_RIMPActionPerformed

    private void btn_ExportExcel_RIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportExcel_RIMActionPerformed
        generadorExcel = new GeneradorExcel();
        generadorExcel.generarExcelIvaRetenidoMesDetalle(tabla_RIM, "RENTENCIONES DE IVA DEL MES", periodo.toUpperCase(), String.valueOf(numAnio));
    }//GEN-LAST:event_btn_ExportExcel_RIMActionPerformed

    /*
    ################INICIA###################
    Funciones: 100% iva acred
     */
    /**
     * Metodo que obtiene y maqueta la tabla de devolucion de Iva
     */
    private void inicializarTablaIva(String numMes, String nombreMes, int mes, int anio) {
        tablaIva = new DefaultTableModel();
        //Titulos para la tabla
        String[] titulos = {"#Factura", "Fecha Factura", "#Poliza", "Fecha Poliza", "Folio Fiscal", "Conceptos XML", "Sub-Total", "IVA", "IVA Retenido", "ISR Retenido",
            "Total", "Cruce: Estado de cuenta", "Pago: Fecha", "Pago: Concepto S.E.C", "Pago: Forma Pago", "RFC Proveedor", "Nombre Proveedor", "Concepto", "Relación con Activ.",
            "Cta. de la que se realiza el pago", "Observaciones"};
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);

        //Clase que obtiene los datos xml
        ivaAcred = new IvaAcredController();
        //url de los documentos Mack
        String URL = "C:\\Users\\Macktronica\\Desktop\\Dac Simulacion\\" + anio + "\\" + numMes;
        String URL_lap = "H:\\Dac Simulacion\\" + anio + "\\" + numMes;
        //correguir sintaxis de ruta, la conexion sql es estable
        String URL_Lx = "/home/horusblack/Documentos/Macktronica/Dac Simulacion/" + anio + "/" + numMes;
        //Lista de objetos xmlDatos

        List<XmlDatos> llenarDatosTabla = ivaAcred.datosDevolucionIva(URL_Lx);
        listPolizaDatos = ivaAcred.solicitudPolizaDatos(mes, anio);

//        if (!listPolizaDatos.isEmpty()) {
//            for (int i = 0; i < listPolizaDatos.size(); i++) {
//                System.out.println("Datos lpd: " + listPolizaDatos.get(i).getNumeroPoliza());
//                System.out.println("Datos lpd: " + listPolizaDatos.get(i).getEjercicio());
//                System.out.println("Datos lpd: " + listPolizaDatos.get(i).getFechaPoliza());
//                System.out.println("Datos lpd: " + listPolizaDatos.get(i).getConceptoPoliza());
//                System.out.println("Datos lpd: " + listPolizaDatos.get(i).getDocumentos());
//                System.out.println("\n");
//            }
//        }
        //Solicitud datos BD
        //checar esta validacion
        if (!llenarDatosTabla.isEmpty()) {
            //llenando la tabla de la info
            System.out.println("tamaño de lista 100 acred: " + llenarDatosTabla.size());
            for (int i = 0; i < llenarDatosTabla.size(); i++) {

                String string = llenarDatosTabla.get(i).getFechaFactura();
                String[] parts = string.split("T");
                String part1 = parts[0];
                String dateFormat = "";
                //No se estan cargando todos los datos
                try {
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(part1);
                    dateFormat = new SimpleDateFormat("dd-MM-yyyy").format(date);

                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Hubo un problema al cargar la fecha: " + ex);
                }

                tablaIva.addRow(new Object[]{"N/D", dateFormat, "N/D", "N/D", llenarDatosTabla.get(i).getFolioFiscal(),
                    llenarDatosTabla.get(i).getConceptoXml(), llenarDatosTabla.get(i).getSubTotal(), llenarDatosTabla.get(i).getIva(), "N/D", "N/D", llenarDatosTabla.get(i).getTotal(),
                    "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D",});

            }

            //Codigo que da la habilidad de ordenar los datos filtrados por orden según lo quiera el cliente
            TableRowSorter<TableModel> ordenTabla = new TableRowSorter<>(tablaIva);
            tablaIvaAcred.setModel(tablaIva);
            tablaIvaAcred.setRowSorter(ordenTabla);

            //Codigo que permite cambiar el tamaño de las columnas de una tabla según se requiera
            TableColumn columna;
            for (int i = 0; i < 8; i++) {
                switch (i) {
                    case 0:
                        //factura
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(50);
                        break;
                    case 1:
                        //Fecha Factura
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(130);
                        break;
                    case 2:
                        //#poliza
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(50);
                        break;
                    case 3:
                        //Fecha Poliza
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(130);
                        break;
                    case 4:
                        //Folio Fiscal
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(270);
                        break;
                    case 5:
                        //Conceptos XML
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(300);
                        break;
                    case 6:
                        //Sub-total
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(70);
                        break;
                    case 7:
                        //Iva
                        columna = tablaIvaAcred.getColumn(titulos[i]);
                        columna.setMinWidth(40);
                        break;
                    default:
                        break;
                }

            }
            lb_100.setText("100% FACTURAS DE IVA ACREDITABLE: " + nombreMes.toUpperCase() + " " + anio);
            btnXmlCargar.setEnabled(true);
        }

    }

    /**
     * Funcion que permite dar formato y valores a la tabla de totales
     */
    private void inicializarTablaTotalIva() {
        defaultTableIva = new DefaultTableModel();
        String[] titulos = {"Gastos 16%", "Compras 0%", "IVA", "Total"};
        Double[] valores = {0.00, 0.00, 0.00, 0.00};
        defaultTableIva.setColumnIdentifiers(titulos);
        defaultTableIva.addRow(valores);
        TableColumn columna;
        tablaTotalIva.setModel(defaultTableIva);
        for (int i = 0; i <= 3; i++) {
            switch (i) {
                case 0:
                    //factura
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(90);
                    break;
                case 1:
                    //Fecha Factura
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(90);
                    break;
                case 2:
                    //#poliza
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(40);
                    break;
                case 3:
                    //Fecha Poliza
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(50);
                    break;
                default:
                    break;
            }

        }

    }

    /**
     * Metodo que preconfigura el diseño del jframe, posicion, tamaño, etc.
     */
    private void preConfiguracion() {
        //Posicion del jframe
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        this.setSize(width / 2, height / 2);
        this.setLocationRelativeTo(null);
        //Elementos adicionales

        txta_Concepto.setVisible(false);
        txta_Concepto.setLineWrap(true);
        btnXmlCargar.setEnabled(false);

    }

    /*
    ################FINALIZA###################
    Funciones: 100% iva acred
     */
 /*
    ################INICIA###################
    Funciones: Auxiliar Iva Acred
     */
    private void inicializarAuxIvaAcred(String numMes, int mes, int anio) {
        tablaIva = new DefaultTableModel();
        //Titulos para la tabla
        String[] titulos = {"Tipo Póliza", "Número Póliza", "Fecha", "Concepto", "Debe", "Haber"};
        totalAuxCred = 0;
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);
        //Clase que obtiene los datos xml
        AuxIvaAcredController auxController = new AuxIvaAcredController();
        DecimalFormat formateador = new DecimalFormat("####.##");
        listAuxIvaAcreds = auxController.solicitudAuxIvaAcred(mes, anio);
        if (!listAuxIvaAcreds.isEmpty()) {
            for (int i = 0; i < listAuxIvaAcreds.size(); i++) {
                String stringDate = listAuxIvaAcreds.get(i).getFecha();
                String newDate = "";
                //System.out.println("String date Aux Iva: "+stringDate);
                if (stringDate != null) {
                    try {
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(stringDate);
                        newDate = new SimpleDateFormat("dd-MM-yyyy").format(date);

                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(this, "Hubo un problema al cargar la fecha: " + ex);
                    }
                }

                tablaIva.addRow(new Object[]{listAuxIvaAcreds.get(i).getTipoPoliza(), listAuxIvaAcreds.get(i).getNoPoliza(), newDate, listAuxIvaAcreds.get(i).getConcepto(),
                    formateador.format(listAuxIvaAcreds.get(i).getDebe()), formateador.format(listAuxIvaAcreds.get(i).getHaber())});
                totalAuxCred += listAuxIvaAcreds.get(i).getDebe();

            }
            TableRowSorter<TableModel> ordenTabla = new TableRowSorter<>(tablaIva);
            tabla_ivaAuxAcred.setModel(tablaIva);
            tabla_ivaAuxAcred.setRowSorter(ordenTabla);
            //Codigo que da la habilidad de ordenar los datos filtrados por orden según lo quiera el cliente
            //Codigo que permite cambiar el tamaño de las columnas de una tabla según se requiera
            TableColumn columna;
            for (int i = 0; i < 6; i++) {
                switch (i) {
                    case 0:
                        //Tipo Poliza
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(90);
                        break;
                    case 1:
                        //Numero Poliza
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(100);
                        break;
                    case 2:
                        //Fecha
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(100);
                        break;
                    case 3:
                        //Concepto
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(800);
                        break;
                    case 4:
                        //Debe
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(100);
                        break;
                    case 5:
                        //Haber
                        columna = tabla_ivaAuxAcred.getColumn(titulos[i]);
                        columna.setMinWidth(100);
                        break;

                    default:
                        break;
                }

            }
            lbT_mesAuxIvaAcred.setText("IVA ACREDITABLE: " + numMes.toUpperCase() + " " + anio);
        }
    }

    private void inicializarTablaTotalAuxAcred(String mes, int anio, double total_cien) {
        tablaIva = new DefaultTableModel();
        String[] titulos = {"", "Descripción", "Totales"};
        tablaIva.setColumnIdentifiers(titulos);
        String complementoCadena = "IVA RETENIDO EN DICIEMBRE Y ENTERADO EN " + mes.toUpperCase() + " " + anio;
        DecimalFormat formateador = new DecimalFormat("####.##");
        tablaIva.addRow(new Object[]{"", "TOTAL AL 100% DE IVA ACREDITABLE", formateador.format(total_cien)});
        tablaIva.addRow(new Object[]{"MAS", complementoCadena, formateador.format(0)});
        tablaIva.addRow(new Object[]{"", "IVA RETENIDO POR CLIENTES EN EL PERIODO", formateador.format(0)});
        tablaIva.addRow(new Object[]{"IGUAL", "", ""});
        tablaIva.addRow(new Object[]{"", "TOTAL DE IVA ACREDITABLE DEL PERIODO", formateador.format(total_cien)});
        tablaIva.addRow(new Object[]{"MENOS", "", ""});
        tablaIva.addRow(new Object[]{"", "IVA CAUSADO Y COBRADO A CLIENTES EN EL PERIODO", formateador.format(0)});
        tablaIva.addRow(new Object[]{"IGUAL", "", ""});
        tablaIva.addRow(new Object[]{"", "SALDO A FAVOR DEL PERIODO SUJETO A DEVOLUCION", formateador.format(0)});
        table_totalAuxIvaAcred.setModel(tablaIva);

    }

    /*
    ################FINALIZA###################
    Funciones: AUXILIAR IVA ACRED bateria 14:43 15:03 (con musica)
     */
 /*
    ################INICIA###################
    Funciones: RETENCION IVA MES
     */
    private void inicializarTablaRetencionIvaMes(String numMes, int mes, int anio) {
        tablaIva = new DefaultTableModel();
        String[] titulos = {"Póliza", "", "Fecha", "Concepto", "RFC Proveedor", "Concepto Gasto", "SubTotal 16%", "Iva Acreditable 16%", "Otros Conceptos Base", "Importe Retenido", "Total Pagado", "Factura"};
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);
        controllerAction = new ControllerAction();
        DecimalFormat formateador = new DecimalFormat("####.##");
        // Esto sale en pantalla con dos decimales, es decir, 3,43
        listRetencionIvaMeses = controllerAction.solicitudRetencionesIvaMes(mes, anio);
        if (!listRetencionIvaMeses.isEmpty()) {
            for (int i = 0; i < listRetencionIvaMeses.size(); i++) {
                String stringDate = listRetencionIvaMeses.get(i).getFecha();
                String newDate = "";

                try {
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(stringDate);
                    newDate = new SimpleDateFormat("dd-MM-yyyy").format(date);

                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Hubo un problema al cargar la fecha: " + ex);
                }

                tablaIva.addRow(new Object[]{listRetencionIvaMeses.get(i).getTipoPoliza(), listRetencionIvaMeses.get(i).getPolCombinada().trim(), newDate, listRetencionIvaMeses.get(i).getConcepto(), "RFC:PENDIENTE",
                    "Concepto Gasto:PENDIENTE", "SubTotal:PENDIENTE", "Iva Acreditable:PENDIENTE", listRetencionIvaMeses.get(i).getConceptosBase(), "Importe Retenido:PENDIENTE", "Total Pagado:PENDIENTE",
                    "Factura:PENDIENTE"});

            }
            TableRowSorter<TableModel> ordenTabla = new TableRowSorter<>(tablaIva);
            tabla_RIM.setModel(tablaIva);
            tabla_RIM.setRowSorter(ordenTabla);
            TableColumn columna;
            for (int i = 0; i < 12; i++) {
                switch (i) {
                    case 0:
                        //Poliza
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(50);
                        break;
                    case 1:
                        //PolizaCombinada
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(35);
                        break;
                    case 2:
                        //Fecha
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(80);
                        break;
                    case 3:
                        //Concepto
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(600);
                        break;
                    case 4:
                        //RFC
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 5:
                        //Concepto Gasto
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(300);
                        break;
                    case 6:
                        //SubTotal
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 7:
                        //Iva Acreditable
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(90);
                        break;
                    case 8:
                        //Otros conceptos
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(300);
                        break;
                    case 9:
                        //Importe Retenido
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 10:
                        //Total pagado
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 11:
                        //Factura
                        columna = tabla_RIM.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    default:
                        break;
                }

            }
            lb_RIM.setText("DETALLE DE IVA RETENIDO DEL MES DE: " + numMes.toUpperCase() + " " + anio);
        }
    }

    /*
    ################FINALIZA###################
    Funciones: RETENCION IVA MES
     */
 /*
    ################INICIA###################
    Funciones: RETENCION IVA MES
     */
    private void inicializarTablaRetencionIvaMesPagadas(String numMes, int mes, int anio) {
        tablaIva = new DefaultTableModel();
        String[] titulos = {"Póliza", "", "Fecha", "Concepto", "RFC Proveedor", "Concepto Gasto", "SubTotal 16%", "Iva Acreditable 16%", "Otros Conceptos Base", "Importe", "Total Pagado", "Factura"};
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);
        controllerAction = new ControllerAction();
        DecimalFormat formateador = new DecimalFormat("####.##");
        // Esto sale en pantalla con dos decimales, es decir, 3,43
        listRetencionIvaPagadaMes = controllerAction.solicitudRetencionesIvaMesPagada(mes, anio);
        if (!listRetencionIvaPagadaMes.isEmpty()) {
            for (int i = 0; i < listRetencionIvaPagadaMes.size(); i++) {
                String stringDate = listRetencionIvaPagadaMes.get(i).getFecha();
                String newDate = "";

                try {
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(stringDate);
                    newDate = new SimpleDateFormat("dd-MM-yyyy").format(date);

                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Hubo un problema al cargar la fecha: " + ex);
                }

                tablaIva.addRow(new Object[]{listRetencionIvaPagadaMes.get(i).getTipoPoliza(), listRetencionIvaPagadaMes.get(i).getPolCombinada().trim(), newDate, listRetencionIvaPagadaMes.get(i).getConcepto(), "RFC:PENDIENTE",
                    "Concepto Gasto:PENDIENTE", "SubTotal:PENDIENTE", "Iva Acreditable:PENDIENTE", listRetencionIvaPagadaMes.get(i).getConceptosBase(), "Importe Retenido:PENDIENTE", "Total Pagado:PENDIENTE",
                    "Factura:PENDIENTE"});

            }
            TableRowSorter<TableModel> ordenTabla = new TableRowSorter<>(tablaIva);
            tabla_RetIvaMesPagada.setModel(tablaIva);
            tabla_RetIvaMesPagada.setRowSorter(ordenTabla);
            TableColumn columna;
            for (int i = 0; i < 12; i++) {
                switch (i) {
                    case 0:
                        //Poliza
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(50);
                        break;
                    case 1:
                        //PolizaCombinada
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(35);
                        break;
                    case 2:
                        //Fecha
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(80);
                        break;
                    case 3:
                        //Concepto
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(600);
                        break;
                    case 4:
                        //RFC
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 5:
                        //Concepto Gasto
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(300);
                        break;
                    case 6:
                        //SubTotal
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 7:
                        //Iva Acreditable
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(90);
                        break;
                    case 8:
                        //Otros conceptos
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(300);
                        break;
                    case 9:
                        //Importe Retenido
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 10:
                        //Total pagado
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    case 11:
                        //Factura
                        columna = tabla_RetIvaMesPagada.getColumn(titulos[i]);
                        columna.setMinWidth(150);
                        break;
                    default:
                        break;
                }

            }
            lb_RIPM.setText("DETALLE DE IVA RETENIDO PAGADO DEL MES DE: " + numMes.toUpperCase() + " " + anio);
        }
    }

    /*
    ################FINALIZA###################
    Funciones: RETENCION IVA MES
     */
 /*
    ################INICIA###################
    Funciones: AUXILIAR DE DEPOSITOS
     */
    private void inicializarTablaAuxDepositos() {
        tablaIva = new DefaultTableModel();
        String[] titulos = {"Fecha", "Concepto", "Debe"};
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);
    }

    /*
    ################FINALIZA###################
    Funciones: AUXILIAR DE DEPOSITOS
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfGlobal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollTotalIva;
    private javax.swing.JScrollPane SpIva;
    private javax.swing.JScrollPane SpIva1;
    private javax.swing.JScrollPane SpIva3;
    private javax.swing.JScrollPane SpIva4;
    private javax.swing.JButton btnGuardarIva;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnProcesarIva;
    private javax.swing.JButton btnXmlCargar;
    private javax.swing.JButton btn_ExportExcel_AuxIvaAcred;
    private javax.swing.JButton btn_ExportExcel_RIM;
    private javax.swing.JButton btn_ExportExcel_RIMP;
    private com.toedter.calendar.JYearChooser calendarAnio;
    private com.toedter.calendar.JMonthChooser calendarMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbT1;
    private javax.swing.JLabel lbT_mesAuxIvaAcred;
    private javax.swing.JLabel lb_100;
    private javax.swing.JLabel lb_RIM;
    private javax.swing.JLabel lb_RIPM;
    private javax.swing.JPanel panelConcepto;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panel_AT_16;
    private javax.swing.JPanel panel_AT_Cero;
    private javax.swing.JPanel panel_AuxDep;
    private javax.swing.JPanel panel_AuxDepositos;
    private javax.swing.JPanel panel_Aux_IA;
    private javax.swing.JPanel panel_CabecerAuxIva;
    private javax.swing.JPanel panel_Cien_FIA;
    private javax.swing.JPanel panel_Det_Iva_Favor;
    private javax.swing.JPanel panel_Filtro;
    private javax.swing.JPanel panel_RIM;
    private javax.swing.JPanel panel_RIPM;
    private javax.swing.JPanel panel_RelacionDep;
    private javax.swing.JPanel panel_RetIvaMes1;
    private javax.swing.JPanel panel_TablaIvaAcred;
    private javax.swing.JPanel panel_contenidoGlobal;
    private javax.swing.JPanel panel_dataIvaAcred;
    private javax.swing.JPanel panel_detRIM;
    private javax.swing.JPanel panel_resultIvaAcred;
    private javax.swing.JScrollPane scrollPaneConcepto;
    private javax.swing.JTable tablaIvaAcred;
    private javax.swing.JTable tablaTotalIva;
    private javax.swing.JTable tabla_AuxDepositos;
    private javax.swing.JTable tabla_RIM;
    private javax.swing.JTable tabla_RetIvaMesPagada;
    private javax.swing.JTable tabla_ivaAuxAcred;
    private javax.swing.JTable table_totalAuxIvaAcred;
    private javax.swing.JTabbedPane tp_Secciones;
    private javax.swing.JTextArea txta_Concepto;
    // End of variables declaration//GEN-END:variables
}
