/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Macktronica
 */
public class jframe_Principal extends javax.swing.JInternalFrame {

    /**
     * Creates new form jframe_Principal
     */
    public jframe_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelPrincipal = new javax.swing.JTabbedPane();
        jPanel_GlobalBancos = new javax.swing.JPanel();
        jsp1 = new javax.swing.JScrollPane();
        jTable_GlobalBancos = new javax.swing.JTable();
        jsp5 = new javax.swing.JScrollPane();
        jTable_GlobalBancos1 = new javax.swing.JTable();
        jPanel_Banorte = new javax.swing.JPanel();
        jsp2 = new javax.swing.JScrollPane();
        jTable_Banorte = new javax.swing.JTable();
        jPanel_VAI = new javax.swing.JPanel();
        jsp3 = new javax.swing.JScrollPane();
        jTable_VAI = new javax.swing.JTable();
        jPanel_Acred = new javax.swing.JPanel();
        jsp4 = new javax.swing.JScrollPane();
        jTable_IvaAcred = new javax.swing.JTable();

        jTable_GlobalBancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {"SUMA DEPOSITOS", null, null, null}
            },
            new String [] {
                "Concepto de los Depositos", "Depositos en Dolares", "Tipo de Cambio", "Depositos en Pesos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_GlobalBancos.setEnabled(false);
        jsp1.setViewportView(jTable_GlobalBancos);

        jTable_GlobalBancos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_GlobalBancos1.setEnabled(false);
        jsp5.setViewportView(jTable_GlobalBancos1);

        javax.swing.GroupLayout jPanel_GlobalBancosLayout = new javax.swing.GroupLayout(jPanel_GlobalBancos);
        jPanel_GlobalBancos.setLayout(jPanel_GlobalBancosLayout);
        jPanel_GlobalBancosLayout.setHorizontalGroup(
            jPanel_GlobalBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GlobalBancosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_GlobalBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_GlobalBancosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jsp5, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_GlobalBancosLayout.setVerticalGroup(
            jPanel_GlobalBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GlobalBancosLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel_GlobalBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_GlobalBancosLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jsp5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        jTabbedPanelPrincipal.addTab("Global Bancos", jPanel_GlobalBancos);

        jTable_Banorte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Concepto según estado de cuenta", "Importe de Depositos o abono", "Referencia", "Piliza COI", "Ventas a tasa 0%", "Ventas a tasa 16%", "Iva Causado", "Trasferencia Entre Cuentas", "Devoluciones De anticipos a proveedor", "Devolución Proveedores", "Intereses del Periodo", "Rechazos de SPEI", "Reembolso de aseguradoras", "Devolución de Impuestos", "Depositos no Identificados", "Total", "Cruce con estado de cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Banorte.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jsp2.setViewportView(jTable_Banorte);

        javax.swing.GroupLayout jPanel_BanorteLayout = new javax.swing.GroupLayout(jPanel_Banorte);
        jPanel_Banorte.setLayout(jPanel_BanorteLayout);
        jPanel_BanorteLayout.setHorizontalGroup(
            jPanel_BanorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp2, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanel_BanorteLayout.setVerticalGroup(
            jPanel_BanorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("Banorte", jPanel_Banorte);

        jTable_VAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jsp3.setViewportView(jTable_VAI);

        javax.swing.GroupLayout jPanel_VAILayout = new javax.swing.GroupLayout(jPanel_VAI);
        jPanel_VAI.setLayout(jPanel_VAILayout);
        jPanel_VAILayout.setHorizontalGroup(
            jPanel_VAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp3, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanel_VAILayout.setVerticalGroup(
            jPanel_VAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("Valor de Actos Ingresos", jPanel_VAI);

        jTable_IvaAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jsp4.setViewportView(jTable_IvaAcred);

        javax.swing.GroupLayout jPanel_AcredLayout = new javax.swing.GroupLayout(jPanel_Acred);
        jPanel_Acred.setLayout(jPanel_AcredLayout);
        jPanel_AcredLayout.setHorizontalGroup(
            jPanel_AcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp4, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanel_AcredLayout.setVerticalGroup(
            jPanel_AcredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp4, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("IVA ACRED Pagos", jPanel_Acred);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Acred;
    private javax.swing.JPanel jPanel_Banorte;
    private javax.swing.JPanel jPanel_GlobalBancos;
    private javax.swing.JPanel jPanel_VAI;
    private javax.swing.JTabbedPane jTabbedPanelPrincipal;
    private javax.swing.JTable jTable_Banorte;
    private javax.swing.JTable jTable_GlobalBancos;
    private javax.swing.JTable jTable_GlobalBancos1;
    private javax.swing.JTable jTable_IvaAcred;
    private javax.swing.JTable jTable_VAI;
    private javax.swing.JScrollPane jsp1;
    private javax.swing.JScrollPane jsp2;
    private javax.swing.JScrollPane jsp3;
    private javax.swing.JScrollPane jsp4;
    private javax.swing.JScrollPane jsp5;
    // End of variables declaration//GEN-END:variables
}
