/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.IvaAcredController;
import Controllers.XmlDatos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframePrincipal extends javax.swing.JFrame {

    private DefaultTableModel tablaIva;
    private DefaultTableModel defaultTableIva;

    /**
     * Creates new form jframePrincipal
     */
    public jframePrincipal() {
        initComponents();
        preConfiguracion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenus = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        SpIva = new javax.swing.JScrollPane();
        tablaIvaAcred = new javax.swing.JTable();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_Concepto = new javax.swing.JTextArea();
        txtXml = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTotalIva = new javax.swing.JTable();
        btnGuardarIva = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIva = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgroEcologia Iva");

        panelMenus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelMenusLayout = new javax.swing.GroupLayout(panelMenus);
        panelMenus.setLayout(panelMenusLayout);
        panelMenusLayout.setHorizontalGroup(
            panelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        panelMenusLayout.setVerticalGroup(
            panelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SpIva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaIvaAcred.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaIvaAcred.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaIvaAcred.setToolTipText("");
        tablaIvaAcred.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaIvaAcred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaIvaAcredMousePressed(evt);
            }
        });
        SpIva.setViewportView(tablaIvaAcred);

        lbTitulo.setText("100% IVA ACREDITABLE");

        txta_Concepto.setColumns(30);
        txta_Concepto.setRows(5);
        txta_Concepto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txta_Concepto.setEnabled(false);
        jScrollPane1.setViewportView(txta_Concepto);

        txtXml.setText("Concepto XML Completo");

        tablaTotalIva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaTotalIva);

        btnGuardarIva.setText("Guardar");

        btnExcel.setText("Generar Excel");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpIva, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo)
                            .addComponent(txtXml)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarIva, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpIva, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcel)
                        .addComponent(btnGuardarIva)))
                .addGap(98, 98, 98)
                .addComponent(txtXml)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuIva.setBackground(new java.awt.Color(153, 204, 255));
        menuIva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuIva.setText("FACTURAS  IVA ACRED");
        menuIva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIvaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuIva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIvaMouseClicked
        tablaIvaAcred.removeAll();
        //Igual habilitar para el de totales
        if (tablaIvaAcred.getRowCount() == 0) {
            inicializarTablaIva();
            inicializarTablaTotalIva();
            lbTitulo.setVisible(true);

        }
    }//GEN-LAST:event_menuIvaMouseClicked

    private void tablaIvaAcredMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIvaAcredMousePressed

        String numCol = "";
        //Obtiene el no. de columna y lo comvierte en String
        numCol = Arrays.toString(tablaIvaAcred.getSelectedColumns());
        //Si es la columna correcta realiza la accion
        if (numCol.equals("[5]")) {
            if (tablaIvaAcred.getSelectedRow() != -1) {
                txta_Concepto.setVisible(true);
                txtXml.setVisible(true);
                //obteniendo el valor de la celda en la coordenada
                String codigo = (String) tablaIva.getValueAt(tablaIvaAcred.getSelectedRow(), 5);
                txta_Concepto.setText(codigo);
                
                // Lo imprimimos en pantalla
            }
        } else {
            txta_Concepto.setVisible(false);
            txtXml.setVisible(false);
        }
    }//GEN-LAST:event_tablaIvaAcredMousePressed

    /**
     * Metodo que obtiene y maqueta la tabla de devolucion de Iva
     */
    private void inicializarTablaIva() {
        tablaIva = new DefaultTableModel();
        //Titulos para la tabla
        String[] titulos = {"#Factura", "Fecha Factura", "#Poliza", "Fecha Poliza", "Folio Fiscal", "Conceptos XML", "Sub-Total", "IVA", "IVA Retenido", "ISR Retenido",
            "Total", "Cruce: Estado de cuenta", "Pago: Fecha", "Pago: Concepto S.E.C", "Pago: Forma Pago", "RFC Proveedor", "Nombre Proveedor", "Concepto", "Relación con Activ.",
            "Cta. de la que se realiza el pago", "Observaciones"};
        //Ingresando titulos
        tablaIva.setColumnIdentifiers(titulos);

        //Clase que obtiene los datos xml
        IvaAcredController ivaAcred = new IvaAcredController();
        //url de los documentos
        String URL = "I:\\Dac\\Enero 01";
        //Lista de objetos xmlDatos
        List<XmlDatos> llenarDatosTabla = ivaAcred.datosDevolucionIva(URL);
        //llenando la tabla de la info
        for (int i = 0; i < llenarDatosTabla.size(); i++) {
            tablaIva.addRow(new Object[]{"N/D", llenarDatosTabla.get(i).getFechaFactura(), "N/D", "N/D", llenarDatosTabla.get(i).getFolioFiscal(),
                llenarDatosTabla.get(i).getConceptoXml(), llenarDatosTabla.get(i).getSubTotal(), "N/D", "N/D", "N/D", llenarDatosTabla.get(i).getTotal(),
                "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D", "N/D",});
        }
        tablaIvaAcred.setModel(tablaIva);
        //tamaño manual
        TableColumn columna;
        for (int i = 0; i < 8; i++) {
            switch (i) {
                case 0:
                    //factura
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(50);
                    break;
                case 1:
                    //Fecha Factura
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(130);
                    break;
                case 2:
                    //#poliza
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(50);
                    break;
                case 3:
                    //Fecha Poliza
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(130);
                    break;
                case 4:
                    //Folio Fiscal
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(270);
                    break;
                case 5:
                    //Conceptos XML
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(300);
                    break;
                case 6:
                    //Sub-total
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(70);
                    break;
                case 7:
                    //Iva
                    columna = tablaIvaAcred.getColumn(titulos[i]);
                    columna.setMinWidth(40);
                    break;
                default:
                    break;
            }

        }

    }

    private void inicializarTablaTotalIva() {
        defaultTableIva = new DefaultTableModel();
        String[] titulos = {"Gastos 16%", "Compras 0%", "IVA", "Total"};
        Double[] valores = {0.00, 0.00, 0.00, 0.00};
        defaultTableIva.setColumnIdentifiers(titulos);
        defaultTableIva.addRow(valores);
        TableColumn columna;
        tablaTotalIva.setModel(defaultTableIva);
        for (int i = 0; i <= 3; i++) {
            switch (i) {
                case 0:
                    //factura
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(90);
                    break;
                case 1:
                    //Fecha Factura
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(90);
                    break;
                case 2:
                    //#poliza
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(40);
                    break;
                case 3:
                    //Fecha Poliza
                    columna = tablaTotalIva.getColumn(titulos[i]);
                    columna.setMinWidth(50);
                    break;
                default:
                    break;
            }

        }

    }

    /**
     * Metodo que preconfigura el diseño del jframe
     */
    private void preConfiguracion() {
        //Posicion del jframe
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        this.setSize(width / 2, height / 2);
        this.setLocationRelativeTo(null);
        //Elementos adicionales
        lbTitulo.setVisible(false);
        txta_Concepto.setVisible(false);
        txta_Concepto.setLineWrap(true);
        txtXml.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SpIva;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnGuardarIva;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenu menuIva;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMenus;
    private javax.swing.JTable tablaIvaAcred;
    private javax.swing.JTable tablaTotalIva;
    private javax.swing.JLabel txtXml;
    private javax.swing.JTextArea txta_Concepto;
    // End of variables declaration//GEN-END:variables
}
